micronaut:
  server:
    port: ${random.port}
grpc:
  server:
    port: ${random.port}
tailrocks:
  client:
    # FIXME replace with the name of the service, for example: payment
    example:
      default-tenant: testing
      # io.micronaut.grpc.server.GrpcServerChannel.NAME
      grpc-channel: grpc-server
